import type { Metadata } from "next";
import { Geist, Geist_Mono, Chelsea_Market } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chelseaMarket = Chelsea_Market({
  weight: "400",
  variable: "--font-chelsea-market",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chelseaMarket.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-1 flex-col">
            <div className="container-wrapper flex flex-1 flex-col px-2">
            <SidebarTrigger />
              <div className="flex scroll-mt-24 items-stretch pb-8 text-[1.05rem] sm:text-[15px] xl:w-full">
                <div className="flex min-w-0 flex-1 flex-col">
                  <div className="h-(--top-spacing) shrink-0"></div>
                  <div className="ms-5 flex w-full max-w-[40rem] min-w-0 flex-1 flex-col gap-6 px-4 py-6 text-neutral-800 md:px-0 lg:py-8 dark:text-neutral-300">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
