import type { Metadata } from "next";
import { Geist, Geist_Mono, Chelsea_Market } from "next/font/google";
import "./globals.css";
import { SiteNavigation } from "@/components/site-navigation"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chelseaMarket = Chelsea_Market({
  weight: "400",
  variable: "--font-chelsea-market",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chelseaMarket.variable} antialiased`}
      >
        <SiteNavigation />
        <main className="mx-auto flex min-h-svh w-full max-w-[1024px] flex-col px-4 pb-8 pt-[74px] text-[1.05rem] sm:text-[15px]">
          <div className="flex w-full max-w-[50rem] flex-1 flex-col gap-6 py-6 lg:py-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
