-- AlterTable
ALTER TABLE `Rock` MODIFY `access` TEXT NULL,
    MODIFY `banned` SMALLINT NULL,
    MODIFY `child_frienly` SMALLINT NULL,
    MODIFY `description` TEXT NULL,
    MODIFY `height` SMALLINT NULL,
    MODIFY `image` VARCHAR(255) NULL,
    MODIFY `lat` DECIMAL(10, 6) NULL,
    MODIFY `lng` DECIMAL(10, 6) NULL,
    MODIFY `nature` TEXT NULL,
    MODIFY `orientation` VARCHAR(50) NULL,
    MODIFY `path_coordinates` JSON NULL,
    MODIFY `preview_image` VARCHAR(255) NULL,
    MODIFY `rain` SMALLINT NULL,
    MODIFY `season` VARCHAR(50) NULL,
    MODIFY `sunny` SMALLINT NULL,
    MODIFY `topo` SMALLINT NULL,
    MODIFY `train` SMALLINT NULL,
    MODIFY `zone` SMALLINT NULL,
    MODIFY `zoom` SMALLINT NULL;
